- name: debug
  debug:
    msg: "{{ansible_all_ipv4_addresses}}"

- name: Install Cloudera 1-Click repository
  yum:
    name: https://archive.cloudera.com/cdh5/one-click-install/redhat/7/x86_64/cloudera-cdh-5-0.x86_64.rpm
    state: installed

# Remove when the bug is fixed
- name: Upload Cloudera "Package does not match intended download" bug fix
  template:
    src: cloudera-cdh5.repo
    dest: /etc/yum.repos.d/cloudera-cdh5.repo

- name: After changing Cloudera repo settings, clean yum's cache
  command: yum clean all

- name: Install zookeeper package
  package:
    name: zookeeper-server
    state: installed

- name: Check if zookeeper has been initialized
  find:
    path: /var/lib/zookeeper
    file_type: directory
    patterns: "*"
  register: zookeeper_data

- name: Initialize server
  command: service zookeeper-server init
  when: zookeeper_data.matched|int == 0

- name: Set zookeeper server id
  template:
    src: myid.j2
    dest: /var/lib/zookeeper/myid
  notify: restart zookeeper

- name: Configure zookeeper
  template:
    src: zoo.j2
    dest: /etc/zookeeper/conf/zoo.cfg
  notify: restart zookeeper

- name: Start zookeeper
  service:
    name: zookeeper-server
    state: started

