---

- name: Create dynamodb table for benchmark results
  dynamodb_table: 
    name: "mqperf-results"
    region: "{{ aws_region }}"
    state: present
    hash_key_name: "test_result_name"
    hash_key_type: STRING
  delegate_to: 127.0.0.1