---
- name: Install libaio module (used for persistence)
  package:
    name:   libaio
    state:  installed
    
- name: Create artemis user
  user:
    name: "{{ artemis_username }}"
    shell: /bin/bash    

- name: Download artemis
  get_url:
    dest: "{{ artemis_download_dest }}"
    url:  "{{ artemis_download_url }}"
    
- name: Unpack archive
  unarchive:
    copy:    no
    dest:    /opt
    src:     "{{ artemis_download_dest }}"
    creates: /opt/{{ artemis_name }}
    owner:   "{{ artemis_username }}"

- name: Create user-friendly link
  file:
    state: link
    src: /opt/{{ artemis_name }}
    dest: /opt/artemis

- set_fact: artemis_broker_master="{{ groups['artemis'][0] }}"
- set_fact: artemis_broker_slave_1="{{ groups['artemis'][1] }}"
- set_fact: artemis_broker_slave_2="{{ groups['artemis'][2] }}"

- name: Set hostname master
  run_once: true
  delegate_to: "{{ item }}"
  hostname:
    name: "artemis_broker_master"
  with_items:
    - "{{ artemis_broker_master }}"

- name: Set hostname slave 1
  run_once: true
  delegate_to: "{{ item }}"
  hostname:
    name: "artemis_broker_slave_1"
  with_items:
    - "{{ artemis_broker_slave_1 }}"

- name: Set hostname slave 2
  run_once: true
  delegate_to: "{{ item }}"
  hostname:
    name: "artemis_broker_slave_2"
  with_items:
    - "{{ artemis_broker_slave_2 }}"

