---
- hosts: localhost
  connection: local
  gather_facts: False

  environment:
    AWS_REGION: "{{ aws_region }}"

  tasks:
  - name: Delete dynamodb table with benchmark results
    dynamodb_table:
      name: "mqperf-results"
      region: "{{ aws_region }}"
      state: absent
      hash_key_name: "test_result_name"