---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, aws_ami_id: ami-061b1560, count: 3, ec2_groups: [ 'ssh_access', 'default'], aws_instance_type: t2.small, ec2_tag_group: Rabbitmq }

- hosts: rabbitmq
  become: true
  roles:
    - role: rabbitmq
      tags: ['rabbitmq']
