---

- hosts: 127.0.0.1
  connection: local
  roles:
    - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'all_access' ], aws_instance_type: t2.micro, ec2_tag_group: Receiver }

- hosts: receiver
  gather_facts: True
  roles:
    - role: mqperf_receiver

- hosts: 127.0.0.1
  connection: local
  roles:
    - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'all_access' ], aws_instance_type: t2.micro, ec2_tag_group: Sender }

- hosts: sender
  gather_facts: True
  roles:
    - role: mqperf_sender