---

- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'default' ], aws_instance_type: t2.micro, ec2_tag_group: Receiver }

- hosts: receiver
  environment:
    DD_API_KEY: "{{ lookup('env', 'DD_API_KEY') }}"
  roles:
  - role: java
  - role: mqperf_receiver
  - role: datadog

- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'default' ], aws_instance_type: t2.micro, ec2_tag_group: Sender }

- hosts: sender
  roles:
  - role: java
  - role: mqperf_sender