---

- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'default'], aws_instance_type: t2.micro, ec2_tag_group: Receiver, instance_profile_name: 'mqperf' }

- hosts: receiver
  roles:
  - role: java
  - role: mqperf_receiver

- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'default'], aws_instance_type: t2.micro, ec2_tag_group: Sender, instance_profile_name: 'mqperf' }

- hosts: sender
  roles:
  - role: java
  - role: mqperf_sender