---

- hosts: sender
  vars:
    test_name: "kafka-25threads.json.j2"
  tasks:
  - name: Set facts for env variables
    set_fact:
      aws_access: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
      aws_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      run_id: "run1"
  - name: Copy test template
    template:
      src: "{{ playbook_dir }}/tests/{{ test_name }}"
      dest: /tmp/test-config.json

- hosts: sender
  environment:
    RUN_ID: "{{ run_id }}"
    AWS_ACCESS_KEY_ID: "{{ aws_access }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret }}"
  tasks:
  - name: Start sender
    shell: nohup /tmp/mqperf.sh start

